# Generated by Django 3.0.7 on 2020-06-24 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_uuid', models.UUIDField()),
                ('data_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('visible', models.BooleanField()),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_values', models.ManyToManyField(to='api.InputValue')),
            ],
        ),
    ]
