# Generated by Django 3.0.7 on 2020-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvalue',
            name='asset_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='inputvalue',
            name='data_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
